"""unique user_id and file_name combination

Revision ID: 1f03959c34f4
Revises: 2c00aa4cd54d
Create Date: 2025-02-22 13:39:53.660719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f03959c34f4'
down_revision = '2c00aa4cd54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_files', schema=None) as batch_op:
        batch_op.drop_index('file_name')
        batch_op.create_unique_constraint('uq_user_files_user_id_file_name', ['user_id', 'file_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_files', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_files_user_id_file_name', type_='unique')
        batch_op.create_index('file_name', ['file_name'], unique=True)

    # ### end Alembic commands ###
