"""adding composite indexing to user_files

Revision ID: 2c00aa4cd54d
Revises: f439f986adc9
Create Date: 2025-02-22 13:33:05.571786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c00aa4cd54d'
down_revision = 'f439f986adc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_files', schema=None) as batch_op:
        batch_op.create_index('user_files_user_id_file_name', ['user_id', 'file_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_files', schema=None) as batch_op:
        batch_op.drop_index('user_files_user_id_file_name')

    # ### end Alembic commands ###
