"""type change of file_size

Revision ID: 63e56bb9c969
Revises: 727914031eab
Create Date: 2025-02-23 13:46:42.118839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63e56bb9c969'
down_revision = '727914031eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_files', schema=None) as batch_op:
        batch_op.alter_column('file_size',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_files', schema=None) as batch_op:
        batch_op.alter_column('file_size',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
