"""added two more columns to user files

Revision ID: 727914031eab
Revises: 1f03959c34f4
Create Date: 2025-02-23 13:35:30.645775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727914031eab'
down_revision = '1f03959c34f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_files', schema=None) as batch_op:
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_type')

    # ### end Alembic commands ###
