"""add user_files

Revision ID: f439f986adc9
Revises: 3120041e9532
Create Date: 2025-02-22 09:15:06.783503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f439f986adc9'
down_revision = '3120041e9532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    with op.batch_alter_table('user_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_files_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_files_user_id'))

    op.drop_table('user_files')
    # ### end Alembic commands ###
